# Internal CI/CD pipeline for the project can be deleted
 include:
 - project: 'grandlinex/templates'
   file: '/stages.yml'
 - project: 'grandlinex/templates'
   file: '/prod/core-bundle.yml'
 - project: 'grandlinex/templates'
   file: '/build/core-bundle.yml'
 - project: 'grandlinex/templates'
   file: '/update/update-glx.yml'
